### ISSUE TITLE
Could not find a valid gem 'sapnwrfc' (>= 0) in any repository

### ISSUE THREAD

**Issue by dpJoker** [fuzziness/sapnwrfc#1]
Hi,
Try to use it on ubuntu, any idea how to fix it ?
gem install sapnwrfc
ERROR:  Could not find a valid gem 'sapnwrfc' (>= 0) in any repository

**Comment by fuzziness** [comment]
you can find it [here](https://rubygems.org/gems/sapnwrfc)

**Comment by dpJoker** [comment]
thanks , please see the error:
gem install sapnwrfc-0.24-x86_64-darwin11.3.0.gem
ERROR:  While executing gem ... (Gem::Exception)
    Unable to find spec for #<Gem::NameTuple sapnwrfc, 0.24, x86_64-darwin-11>

```
`
$ gem install sapnwrfc-0.24-x86_64-darwin11.3.0.gem --debug -V
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at */.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/resolv.rb:171 - LoadError
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=sapnwrfc
200 OK
Exception `Gem::Exception' at */.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/source/local.rb:107 - Unable to find spec for #<Gem::NameTuple sapnwrfc, 0.24, x86_64-darwin-11>
ERROR:  While executing gem ... (Gem::Exception)
    Unable to find spec for #<Gem::NameTuple sapnwrfc, 0.24, x86_64-darwin-11>
    /home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/source/local.rb:107:in `fetch_spec'
    /home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/resolver/index_specification.rb:65:in `spec'
    /home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/resolver/specification.rb:104:in `installable_platform?'
    /home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/platform.rb:35:in `installable?'
    /home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/resolver.rb:224:in `block in select_local_platforms'
    /home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/resolver.rb:223:in `select'
    /home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/resolver.rb:223:in `select_local_platforms'
    /home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/resolver.rb:214:in `find_possible'
    /home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/resolver.rb:229:in `search_for'
    /home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:130:in `block (2 levels) in <class:Resolution>'
    /home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:180:in `initial_state'
    /home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:99:in `start_resolution'
    /home/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:62:in `resolve'
    .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:41:in `resolve'
    .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/resolver.rb:191:in `resolve'
    .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/request_set.rb:363:in `resolve'
    .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/dependency_installer.rb:484:in `resolve_dependencies'
    .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/commands/install_command.rb:239:in `install_gem'
    /.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/commands/install_command.rb:300:in `block in install_gems'
    .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `each'
    /.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `install_gems'
    .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/commands/install_command.rb:203:in `execute'
    .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/command.rb:308:in `invoke_with_build_args'
    .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'
    .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/command_manager.rb:139:in `run'
    .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'
    /.rvm/rubies/ruby-2.3.0/bin/gem:21:in `<main>'
`
`
```

**Comment by fuzziness** [comment]
gem is definitively old; have you tried to checkout sources & build it yourself?
